#!/usr/bin/bash

export LAST_TAG=$(git describe --tags --abbrev=0)
export CHANGELOG_FILE=FKM/changelog
export NUM_COMMITS=25

echo "Autogenerated on $(date --utc)" > "$CHANGELOG_FILE"
echo >> "$CHANGELOG_FILE"
git log "$LAST_TAG"..HEAD --oneline --format=oneline -n$NUM_COMMITS | sed 's/^.\{13\}//g' | sed 's/^/* /' >> "$CHANGELOG_FILE"
